version: '3.8'

services:
  n8n:
    image: docker.n8n.io/n8nio/n8n:latest
    container_name: n8n
    restart: unless-stopped
    ports:
      - "5678:5678"
    environment:
      - N8N_HOST=n8n.secure-svr.net
      - N8N_PORT=5678
      - N8N_PROTOCOL=https
      - WEBHOOK_URL=https://n8n.secure-svr.net/
      - GENERIC_TIMEZONE=America/Chicago
      - N8N_METRICS=true
      - N8N_TRUST_PROXY=true
    volumes:
      - n8n_data:/home/node/.n8n
      - ./config:/config:ro

volumes:
  n8n_data:
    name: n8n_data
